K = NumberField(x-1,'a')
y = polygen(K,'t')
M = K.extension(y**2+2,'b')
c2 = M.gen()
t = polygen(M,'y')
L = M.extension(t**3 - 57*t + 76*c2,'c')
SK = sum([K.primes_above(p) for p in [2,1                                                                       ]],[])
SL = sum([L.primes_above(p) for p in SK],[])
SunitL = L.S_unit_group(S=SL)
Gl,Gm = Norm_subgroup_division_field(SK,SL)
B = 360
